const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  LevelFormat, PageBreak
} = require('docx');
const fs = require('fs');

const BRAND_BLUE = "1A3C5E";
const BRAND_GREEN = "0F7B6C";
const BRAND_ORANGE = "E67E22";
const LIGHT_BG = "EBF5FB";
const CODE_BG = "1E1E2E";

const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const borders = { top: border, bottom: border, left: border, right: border };

function h1(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 400, after: 200 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: BRAND_BLUE, space: 4 } },
    children: [new TextRun({ text, bold: true, size: 32, color: BRAND_BLUE, font: "Arial" })]
  });
}
function h2(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 320, after: 160 },
    children: [new TextRun({ text, bold: true, size: 26, color: BRAND_BLUE, font: "Arial" })]
  });
}
function h3(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, bold: true, size: 22, color: BRAND_GREEN, font: "Arial" })]
  });
}
function para(text, opts = {}) {
  return new Paragraph({
    spacing: { before: 80, after: 120 },
    children: [new TextRun({ text, size: 22, font: "Arial", ...opts })]
  });
}
function bullet(text) {
  return new Paragraph({
    numbering: { reference: "bullets", level: 0 },
    spacing: { before: 60, after: 60 },
    children: [new TextRun({ text, size: 22, font: "Arial" })]
  });
}
function code(text) {
  return new Paragraph({
    spacing: { before: 80, after: 80 },
    shading: { fill: "F0F4F8", type: ShadingType.CLEAR },
    indent: { left: 360 },
    children: [new TextRun({ text, size: 18, font: "Courier New", color: "2D3748" })]
  });
}
function infoTable(rows) {
  return new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [3000, 6360],
    rows: rows.map(([l, v]) => new TableRow({ children: [
      new TableCell({ borders, width: { size: 3000, type: WidthType.DXA }, shading: { fill: LIGHT_BG, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: l, bold: true, size: 20, font: "Arial" })] })] }),
      new TableCell({ borders, width: { size: 6360, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: v, size: 20, font: "Arial" })] })] })
    ]}))
  });
}
function pageBreak() { return new Paragraph({ children: [new PageBreak()] }); }

const doc = new Document({
  numbering: {
    config: [
      { reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "\u2022", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      { reference: "numbers", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] }
    ]
  },
  styles: {
    default: { document: { run: { font: "Arial", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 32, bold: true, font: "Arial", color: BRAND_BLUE }, paragraph: { spacing: { before: 400, after: 200 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 26, bold: true, font: "Arial", color: BRAND_BLUE }, paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 22, bold: true, font: "Arial", color: BRAND_GREEN }, paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 2 } }
    ]
  },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
    children: [
      new Paragraph({ spacing: { before: 2000, after: 200 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "VERIFAI", bold: true, size: 72, font: "Arial", color: BRAND_BLUE })] }),
      new Paragraph({ spacing: { before: 0, after: 120 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Fake News Detection Platform", size: 36, font: "Arial", color: BRAND_GREEN })] }),
      new Paragraph({ spacing: { before: 400, after: 80 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "TECHNICAL REQUIREMENTS DOCUMENT (TRD)", bold: true, size: 28, font: "Arial", color: "555555" })] }),
      new Paragraph({ spacing: { before: 80, after: 80 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Version 1.0  |  June 2026  |  ENGINEERING CONFIDENTIAL", size: 20, font: "Arial", color: "888888" })] }),
      pageBreak(),
      h1("1. System Architecture Overview"),
      para("VERIFAI is built on a cloud-native, microservices architecture optimized for high throughput, low latency, and horizontal scalability. The system is divided into five primary layers: Client Tier, API Gateway, Application Services, ML Pipeline, and Data Layer."),
      h2("1.1 High-Level Architecture"),
      para("Layer 1 — Client Tier:", { bold: true }),
      bullet("Next.js 14 (App Router) — Web Application — Vercel Edge Network"),
      bullet("React Native 0.74 — iOS & Android Mobile Apps"),
      bullet("Chrome Extension (Manifest V3) — Browser Plugin"),
      bullet("REST/GraphQL API clients for enterprise integrations"),
      para("Layer 2 — API Gateway & Edge:", { bold: true }),
      bullet("Vercel Edge Functions — geographic routing and caching"),
      bullet("Kong API Gateway — rate limiting, auth validation, request routing"),
      bullet("Cloudflare WAF — DDoS protection and bot mitigation"),
      bullet("Redis (Upstash) — response caching layer (TTL: 1 hour for identical URLs)"),
      para("Layer 3 — Application Services (Supabase Edge Functions / Node.js):", { bold: true }),
      bullet("Auth Service — Supabase Auth (JWT, OAuth, magic links)"),
      bullet("Analysis Orchestrator — routes requests to appropriate ML models"),
      bullet("URL Scraping Service — Playwright headless browser + Cheerio"),
      bullet("Source Intelligence Service — credibility database lookups"),
      bullet("Notification Service — email (Resend), push (FCM), webhooks"),
      bullet("Report Generation Service — PDF/Excel export engine"),
      para("Layer 4 — ML Pipeline (Python / FastAPI):", { bold: true }),
      bullet("BERT/RoBERTa inference service — text classification"),
      bullet("Image analysis service — ViT + CLIP models"),
      bullet("Fact-check cross-reference engine — ElasticSearch"),
      bullet("Bias detection engine — political stance classifier"),
      bullet("Model serving — TorchServe on AWS ECS (Fargate)"),
      para("Layer 5 — Data Layer:", { bold: true }),
      bullet("Supabase PostgreSQL — primary relational database"),
      bullet("Supabase Storage — file uploads, cached article content"),
      bullet("Supabase Realtime — live dashboard updates via WebSocket"),
      bullet("ElasticSearch — full-text search on 10M+ fact-check records"),
      bullet("Redis — caching, session storage, rate limit counters"),
      pageBreak(),
      h1("2. Complete Technology Stack"),
      h2("2.1 Frontend"),
      new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: [2400, 2400, 4560],
        rows: [
          new TableRow({ children: [
            ...["Technology", "Version", "Purpose"].map(t => new TableCell({ borders, shading: { fill: BRAND_BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: t, bold: true, size: 20, font: "Arial", color: "FFFFFF" })] })] }))
          ]}),
          ...[
            ["Next.js 14", "14.2.x", "Full-stack React framework, SSR, App Router, API routes"],
            ["React", "18.3.x", "Component-based UI library"],
            ["TypeScript", "5.4.x", "Type-safe JavaScript throughout codebase"],
            ["Tailwind CSS", "3.4.x", "Utility-first CSS framework"],
            ["shadcn/ui", "Latest", "Accessible, customizable UI component library"],
            ["Framer Motion", "11.x", "Page transitions and micro-animations"],
            ["Recharts", "2.12.x", "Data visualization and analytics charts"],
            ["React Query", "5.x", "Server state management and caching"],
            ["Zustand", "4.5.x", "Client-side state management"],
            ["React Hook Form", "7.x", "Form handling with validation"],
            ["Zod", "3.x", "Schema validation (shared with backend)"],
            ["React Dropzone", "14.x", "File upload drag-and-drop interface"],
          ].map(([tech, ver, purpose]) => new TableRow({ children: [
            new TableCell({ borders, width: { size: 2400, type: WidthType.DXA }, shading: { fill: LIGHT_BG, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: tech, bold: true, size: 18, font: "Arial" })] })] }),
            new TableCell({ borders, width: { size: 2400, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: ver, size: 18, font: "Arial", color: BRAND_GREEN })] })] }),
            new TableCell({ borders, width: { size: 4560, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: purpose, size: 18, font: "Arial" })] })] }),
          ]}))
        ]
      }),
      h2("2.2 Backend"),
      new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: [2400, 2400, 4560],
        rows: [
          new TableRow({ children: [
            ...["Technology", "Version", "Purpose"].map(t => new TableCell({ borders, shading: { fill: BRAND_GREEN, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: t, bold: true, size: 20, font: "Arial", color: "FFFFFF" })] })] }))
          ]}),
          ...[
            ["Supabase", "Latest", "BaaS: Auth, PostgreSQL, Storage, Realtime, Edge Functions"],
            ["PostgreSQL", "15.x", "Primary relational database via Supabase"],
            ["Node.js", "20 LTS", "Runtime for API services and Edge Functions"],
            ["Python", "3.11", "ML inference services and data pipeline"],
            ["FastAPI", "0.111.x", "High-performance REST API for ML services"],
            ["Deno", "1.44.x", "Supabase Edge Functions runtime"],
            ["Redis (Upstash)", "7.x", "Caching, sessions, rate limiting"],
            ["ElasticSearch", "8.x", "Full-text search on fact-check corpus"],
            ["Playwright", "1.44.x", "Headless browser for article scraping"],
            ["Bull / BullMQ", "5.x", "Job queues for async processing"],
          ].map(([tech, ver, purpose]) => new TableRow({ children: [
            new TableCell({ borders, width: { size: 2400, type: WidthType.DXA }, shading: { fill: "EAFAF1", type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: tech, bold: true, size: 18, font: "Arial" })] })] }),
            new TableCell({ borders, width: { size: 2400, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: ver, size: 18, font: "Arial", color: BRAND_GREEN })] })] }),
            new TableCell({ borders, width: { size: 4560, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: purpose, size: 18, font: "Arial" })] })] }),
          ]}))
        ]
      }),
      h2("2.3 ML & AI Stack"),
      new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: [2400, 2400, 4560],
        rows: [
          new TableRow({ children: [
            ...["Technology", "Version", "Purpose"].map(t => new TableCell({ borders, shading: { fill: BRAND_ORANGE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: t, bold: true, size: 20, font: "Arial", color: "FFFFFF" })] })] }))
          ]}),
          ...[
            ["PyTorch", "2.3.x", "Deep learning framework for model training and inference"],
            ["Hugging Face Transformers", "4.41.x", "Pre-trained BERT, RoBERTa, ViT models"],
            ["BERT (fine-tuned)", "bert-base-uncased", "Primary text classification model"],
            ["RoBERTa", "roberta-large", "Secondary ensemble model for high accuracy"],
            ["CLIP", "ViT-L/14", "Image-text alignment for visual misinformation"],
            ["TorchServe", "0.10.x", "ML model serving infrastructure"],
            ["NLTK / spaCy", "3.7.x", "NLP preprocessing pipeline"],
            ["Scikit-learn", "1.5.x", "Feature engineering and ensemble methods"],
            ["LangChain", "0.2.x", "LLM chains for explanation generation"],
            ["Sentence Transformers", "3.x", "Semantic similarity for cross-reference"],
          ].map(([tech, ver, purpose]) => new TableRow({ children: [
            new TableCell({ borders, width: { size: 2400, type: WidthType.DXA }, shading: { fill: "FEF9E7", type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: tech, bold: true, size: 18, font: "Arial" })] })] }),
            new TableCell({ borders, width: { size: 2400, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: ver, size: 18, font: "Arial", color: BRAND_ORANGE })] })] }),
            new TableCell({ borders, width: { size: 4560, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: purpose, size: 18, font: "Arial" })] })] }),
          ]}))
        ]
      }),
      pageBreak(),
      h1("3. Database Schema (Supabase / PostgreSQL)"),
      h2("3.1 Schema Design Principles"),
      bullet("All tables use UUID primary keys for security and distributed compatibility"),
      bullet("Row Level Security (RLS) enabled on all tables — users access only their own data"),
      bullet("Soft deletes on critical tables (deleted_at timestamp, not hard DELETE)"),
      bullet("Audit trail via created_at, updated_at timestamps on all tables"),
      bullet("Foreign keys with cascade deletes where appropriate"),
      bullet("Indexes on all frequently queried columns (user_id, created_at, status)"),
      h2("3.2 Core Tables"),
      h3("3.2.1 users (managed by Supabase Auth, extended via profiles)"),
      code("CREATE TABLE profiles ("),
      code("  id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,"),
      code("  username     TEXT UNIQUE NOT NULL,"),
      code("  full_name    TEXT,"),
      code("  avatar_url   TEXT,"),
      code("  tier         TEXT DEFAULT 'free' CHECK (tier IN ('free','pro','enterprise')),"),
      code("  api_key      TEXT UNIQUE,"),
      code("  api_calls_today INT DEFAULT 0,"),
      code("  total_analyses  INT DEFAULT 0,"),
      code("  created_at   TIMESTAMPTZ DEFAULT NOW(),"),
      code("  updated_at   TIMESTAMPTZ DEFAULT NOW()"),
      code(");"),
      h3("3.2.2 analyses"),
      code("CREATE TABLE analyses ("),
      code("  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),"),
      code("  user_id         UUID REFERENCES profiles(id) ON DELETE CASCADE,"),
      code("  input_type      TEXT NOT NULL CHECK (input_type IN ('url','text','image','social')),"),
      code("  input_content   TEXT NOT NULL,"),
      code("  article_title   TEXT,"),
      code("  article_author  TEXT,"),
      code("  source_domain   TEXT,"),
      code("  verdict         TEXT NOT NULL CHECK (verdict IN ('real','fake','misleading','satire','unverified')),"),
      code("  credibility_score SMALLINT CHECK (credibility_score BETWEEN 0 AND 100),"),
      code("  confidence      NUMERIC(5,2),"),
      code("  bias_score      SMALLINT,"),
      code("  sentiment_score NUMERIC(5,2),"),
      code("  analysis_data   JSONB,"),
      code("  model_version   TEXT,"),
      code("  processing_ms   INT,"),
      code("  is_public       BOOLEAN DEFAULT FALSE,"),
      code("  share_token     TEXT UNIQUE,"),
      code("  deleted_at      TIMESTAMPTZ,"),
      code("  created_at      TIMESTAMPTZ DEFAULT NOW()"),
      code(");"),
      code("CREATE INDEX idx_analyses_user_id ON analyses(user_id);"),
      code("CREATE INDEX idx_analyses_verdict ON analyses(verdict);"),
      code("CREATE INDEX idx_analyses_created ON analyses(created_at DESC);"),
      h3("3.2.3 sources"),
      code("CREATE TABLE sources ("),
      code("  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),"),
      code("  domain          TEXT UNIQUE NOT NULL,"),
      code("  name            TEXT NOT NULL,"),
      code("  credibility     SMALLINT CHECK (credibility BETWEEN 0 AND 100),"),
      code("  bias_label      TEXT,"),
      code("  country         TEXT,"),
      code("  category        TEXT[],"),
      code("  is_satire       BOOLEAN DEFAULT FALSE,"),
      code("  last_reviewed   TIMESTAMPTZ,"),
      code("  metadata        JSONB"),
      code(");"),
      h3("3.2.4 subscriptions"),
      code("CREATE TABLE subscriptions ("),
      code("  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),"),
      code("  user_id         UUID UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,"),
      code("  stripe_customer_id  TEXT UNIQUE,"),
      code("  stripe_sub_id       TEXT UNIQUE,"),
      code("  tier            TEXT NOT NULL CHECK (tier IN ('free','pro','enterprise')),"),
      code("  status          TEXT NOT NULL CHECK (status IN ('active','canceled','past_due')),"),
      code("  current_period_start  TIMESTAMPTZ,"),
      code("  current_period_end    TIMESTAMPTZ,"),
      code("  created_at      TIMESTAMPTZ DEFAULT NOW()"),
      code(");"),
      pageBreak(),
      h1("4. API Design Specification"),
      h2("4.1 REST API Base URL"),
      code("Production:  https://api.verifai.ai/v1"),
      code("Staging:     https://api-staging.verifai.ai/v1"),
      h2("4.2 Authentication"),
      para("All API requests require a Bearer token in the Authorization header:"),
      code("Authorization: Bearer <supabase_jwt_or_api_key>"),
      h2("4.3 Core Endpoints"),
      new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: [1200, 3000, 2160, 3000],
        rows: [
          new TableRow({ children: [
            ...["Method", "Endpoint", "Auth", "Description"].map(t => new TableCell({ borders, shading: { fill: BRAND_BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: t, bold: true, size: 18, font: "Arial", color: "FFFFFF" })] })] }))
          ]}),
          ...[
            ["POST", "/analyses", "Required", "Create new analysis (URL, text, image)"],
            ["GET", "/analyses", "Required", "List user's analysis history (paginated)"],
            ["GET", "/analyses/:id", "Optional", "Get specific analysis by ID or share token"],
            ["DELETE", "/analyses/:id", "Required", "Soft-delete an analysis"],
            ["POST", "/analyses/batch", "Pro+", "Batch analyze up to 50 URLs"],
            ["GET", "/sources/:domain", "Public", "Get credibility data for a domain"],
            ["GET", "/sources/search", "Public", "Search source database"],
            ["GET", "/trends", "Public", "Current misinformation trends"],
            ["GET", "/profile", "Required", "Get current user profile"],
            ["PUT", "/profile", "Required", "Update user profile"],
            ["POST", "/profile/api-key", "Required", "Generate/rotate API key"],
            ["GET", "/stats", "Required", "User usage statistics"],
            ["POST", "/webhooks", "Enterprise", "Configure webhook endpoints"],
          ].map(([method, endpoint, auth, desc]) => new TableRow({ children: [
            new TableCell({ borders, width: { size: 1200, type: WidthType.DXA }, shading: { fill: method === "POST" ? "EBF5FB" : method === "GET" ? "EAFAF1" : method === "DELETE" ? "FDEDEC" : "FEF9E7", type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: method, bold: true, size: 18, font: "Courier New", color: method === "POST" ? "1A3C5E" : method === "DELETE" ? "C0392B" : "0F7B6C" })] })] }),
            new TableCell({ borders, width: { size: 3000, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: endpoint, size: 18, font: "Courier New" })] })] }),
            new TableCell({ borders, width: { size: 2160, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: auth, size: 18, font: "Arial" })] })] }),
            new TableCell({ borders, width: { size: 3000, type: WidthType.DXA }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ children: [new TextRun({ text: desc, size: 18, font: "Arial" })] })] }),
          ]}))
        ]
      }),
      h2("4.4 Sample API Request / Response"),
      h3("POST /v1/analyses — URL Analysis"),
      code("// Request body"),
      code("{"),
      code("  \"input_type\": \"url\","),
      code("  \"content\": \"https://example.com/breaking-news-article\","),
      code("  \"options\": {"),
      code("    \"include_source_rating\": true,"),
      code("    \"include_bias_analysis\": true,"),
      code("    \"language\": \"en\""),
      code("  }"),
      code("}"),
      para(""),
      code("// Response (HTTP 201 Created)"),
      code("{"),
      code("  \"id\": \"550e8400-e29b-41d4-a716-446655440000\","),
      code("  \"verdict\": \"misleading\","),
      code("  \"credibility_score\": 28,"),
      code("  \"confidence\": 0.87,"),
      code("  \"article\": {"),
      code("    \"title\": \"Shocking study reveals coffee causes...\","),
      code("    \"author\": \"Unknown\""),
      code("    \"published_at\": \"2026-06-20T10:30:00Z\""),
      code("  },"),
      code("  \"source\": {"),
      code("    \"domain\": \"example.com\","),
      code("    \"credibility\": 22,"),
      code("    \"bias\": \"far-right\","),
      code("    \"known_issues\": [\"clickbait\", \"misleading_headlines\"]"),
      code("  },"),
      code("  \"flags\": ["),
      code("    { \"type\": \"emotional_language\", \"severity\": \"high\" },"),
      code("    { \"type\": \"missing_sources\", \"severity\": \"medium\" }"),
      code("  ],"),
      code("  \"processing_ms\": 1847,"),
      code("  \"share_url\": \"https://verifai.ai/r/abc123def\""),
      code("}"),
      pageBreak(),
      h1("5. ML Pipeline Architecture"),
      h2("5.1 Text Classification Pipeline"),
      para("Every article analysis flows through a 5-stage pipeline:"),
      para("Stage 1 — Preprocessing:", { bold: true }),
      bullet("URL fetch and HTML parsing via Playwright + Readability.js"),
      bullet("Text cleaning: remove HTML tags, normalize Unicode, fix encoding"),
      bullet("Language detection via langdetect"),
      bullet("Tokenization using HuggingFace AutoTokenizer"),
      para("Stage 2 — Feature Extraction:", { bold: true }),
      bullet("BERT embeddings (768-dimensional vector)"),
      bullet("Linguistic features: sentence count, avg word length, exclamation density"),
      bullet("Sentiment features: VADER + transformer-based sentiment score"),
      bullet("Source metadata features: domain age, Alexa rank, HTTPS status"),
      para("Stage 3 — Model Ensemble:", { bold: true }),
      bullet("Primary: Fine-tuned BERT (bert-base-uncased) on LIAR + FakeNewsNet datasets"),
      bullet("Secondary: RoBERTa-large for high-confidence cross-validation"),
      bullet("Tertiary: XGBoost on engineered features"),
      bullet("Ensemble: weighted averaging (BERT 50%, RoBERTa 35%, XGBoost 15%)"),
      para("Stage 4 — Cross-Reference Check:", { bold: true }),
      bullet("Extract key claims using NER (spaCy: PERSON, ORG, DATE, EVENT entities)"),
      bullet("Semantic search against 10M+ fact-check records in ElasticSearch"),
      bullet("Sources: PolitiFact, Snopes, FactCheck.org, AFP Fact Check, Boom Live"),
      bullet("Contradiction detection using MNLI entailment models"),
      para("Stage 5 — Scoring & Explanation:", { bold: true }),
      bullet("Aggregate score: weighted combination of all model outputs"),
      bullet("SHAP values for explainability — which features drove the verdict"),
      bullet("LLM-generated plain-English explanation via GPT-4o / Claude"),
      bullet("Confidence calibration using temperature scaling"),
      h2("5.2 Model Performance Benchmarks"),
      infoTable([
        ["Dataset", "LIAR Benchmark (12,836 statements)"],
        ["BERT Accuracy", "91.3%"],
        ["RoBERTa Accuracy", "93.1%"],
        ["Ensemble Accuracy", "94.2%"],
        ["False Positive Rate", "< 4.5%"],
        ["Inference Time (CPU)", "~800ms per article"],
        ["Inference Time (GPU)", "~120ms per article"],
        ["Model Size (BERT)", "440MB"],
        ["Model Size (RoBERTa)", "1.3GB"],
      ]),
      pageBreak(),
      h1("6. Supabase Configuration"),
      h2("6.1 Project Setup"),
      bullet("Project: verifai-prod (Region: ap-south-1 — Mumbai for Indian user base)"),
      bullet("Database: PostgreSQL 15 with pgvector extension enabled"),
      bullet("Realtime: Enabled on analyses table for live dashboard updates"),
      bullet("Storage: Buckets for article_cache and user_uploads (max 10MB)"),
      bullet("Edge Functions: analyse_url, analyse_text, generate_report, send_alerts"),
      h2("6.2 Row Level Security Policies"),
      code("-- Users can only see their own analyses"),
      code("CREATE POLICY \"user_analyses_select\" ON analyses"),
      code("  FOR SELECT USING (auth.uid() = user_id OR is_public = true);"),
      code(""),
      code("-- Users can only insert their own analyses"),
      code("CREATE POLICY \"user_analyses_insert\" ON analyses"),
      code("  FOR INSERT WITH CHECK (auth.uid() = user_id);"),
      code(""),
      code("-- Users can only delete their own analyses"),
      code("CREATE POLICY \"user_analyses_delete\" ON analyses"),
      code("  FOR DELETE USING (auth.uid() = user_id);"),
      h2("6.3 Edge Functions"),
      h3("analyse-url Function (Deno)"),
      code("// supabase/functions/analyse-url/index.ts"),
      code("import { serve } from 'https://deno.land/std@0.208.0/http/server.ts'"),
      code("import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'"),
      code(""),
      code("serve(async (req) => {"),
      code("  const { url } = await req.json()"),
      code("  const supabase = createClient("),
      code("    Deno.env.get('SUPABASE_URL')!,"),
      code("    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!"),
      code("  )"),
      code("  // 1. Check Redis cache"),
      code("  // 2. Call ML service (FastAPI)"),
      code("  // 3. Store result in Supabase"),
      code("  // 4. Return analysis"),
      code("  return new Response(JSON.stringify(result), { headers: { 'Content-Type': 'application/json' } })"),
      code("})"),
      pageBreak(),
      h1("7. Deployment & Infrastructure"),
      h2("7.1 Deployment Architecture"),
      infoTable([
        ["Web App", "Vercel — automatic deployments from main branch, preview URLs for PRs"],
        ["Edge Functions", "Supabase Edge Functions — deployed via Supabase CLI"],
        ["ML Services", "AWS ECS Fargate — containerized Python FastAPI services"],
        ["Database", "Supabase PostgreSQL — managed, auto-backups, point-in-time recovery"],
        ["CDN", "Vercel Edge Network + Cloudflare CDN (50+ global PoPs)"],
        ["Caching", "Upstash Redis — serverless, globally distributed"],
        ["Monitoring", "Datadog APM + Supabase Dashboard + Sentry error tracking"],
        ["CI/CD", "GitHub Actions — lint, test, build, deploy pipeline"],
      ]),
      h2("7.2 Environment Variables"),
      code("# .env.local (Next.js)"),
      code("NEXT_PUBLIC_SUPABASE_URL=https://xxx.supabase.co"),
      code("NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJ..."),
      code("SUPABASE_SERVICE_ROLE_KEY=eyJ..."),
      code("ML_SERVICE_URL=https://ml.verifai.ai"),
      code("ML_SERVICE_API_KEY=vfy_ml_..."),
      code("REDIS_URL=rediss://xxx.upstash.io:6380"),
      code("STRIPE_SECRET_KEY=sk_live_..."),
      code("RESEND_API_KEY=re_..."),
      h2("7.3 CI/CD Pipeline (GitHub Actions)"),
      code("# .github/workflows/deploy.yml"),
      code("on: push: branches: [main]"),
      code("jobs:"),
      code("  test:"),
      code("    runs-on: ubuntu-latest"),
      code("    steps:"),
      code("      - uses: actions/checkout@v4"),
      code("      - run: npm ci && npm run test"),
      code("      - run: npm run lint"),
      code("      - run: npx tsc --noEmit"),
      code("  deploy:"),
      code("    needs: test"),
      code("    steps:"),
      code("      - uses: amondnet/vercel-action@v25"),
      code("      - run: supabase functions deploy --project-ref $PROJECT_REF"),
      pageBreak(),
      h1("8. Security Architecture"),
      h2("8.1 Authentication Flow"),
      bullet("All auth via Supabase Auth — no custom auth code"),
      bullet("JWTs signed with RS256, 1-hour expiry"),
      bullet("Refresh tokens rotated on each use (rotation interval: 60 minutes)"),
      bullet("API keys stored as bcrypt hashes in database (never in plain text)"),
      bullet("OAuth tokens stored in Supabase secure sessions, never in localStorage"),
      h2("8.2 Input Validation"),
      bullet("All inputs validated with Zod schemas on both client and server"),
      bullet("URL validation: must be http/https, no private IP ranges (SSRF prevention)"),
      bullet("Text input: sanitized with DOMPurify, max length enforced"),
      bullet("File uploads: magic byte verification (not just extension check), max 10MB"),
      bullet("SQL injection: impossible via Supabase parameterized queries"),
      h2("8.3 Rate Limiting"),
      infoTable([
        ["Free Tier", "20 analyses/day, 100 API calls/hour"],
        ["Pro Tier", "Unlimited analyses, 1000 API calls/hour"],
        ["Enterprise Tier", "Unlimited analyses, unlimited API calls"],
        ["Unauthenticated", "5 analyses/day (IP-based)"],
        ["Rate limit store", "Redis (Upstash) with sliding window algorithm"],
      ]),
      h2("8.4 Data Privacy"),
      bullet("No PII used in ML model training"),
      bullet("Article content cached for 24 hours only, then purged"),
      bullet("Users can download all their data (GDPR Article 20)"),
      bullet("Account deletion purges all data within 30 days (GDPR Article 17)"),
      bullet("India DPDP Act 2023 compliant — data localization in ap-south-1"),
      pageBreak(),
      h1("9. Testing Strategy"),
      h2("9.1 Testing Pyramid"),
      infoTable([
        ["Unit Tests", "Jest + React Testing Library — all components and utility functions"],
        ["Integration Tests", "Supertest — all API endpoints with mock ML service"],
        ["E2E Tests", "Playwright — critical user journeys (register, analyze, subscribe)"],
        ["ML Model Tests", "PyTest — accuracy benchmarks, edge cases, adversarial inputs"],
        ["Load Tests", "k6 — simulate 10,000 concurrent users on analysis endpoint"],
        ["Security Tests", "OWASP ZAP — automated DAST scanning on every release"],
      ]),
      h2("9.2 Coverage Targets"),
      bullet("Unit test coverage: > 80% lines"),
      bullet("Critical paths (auth, payment, analysis): 100% coverage"),
      bullet("E2E coverage: all P0 user stories covered"),
      bullet("ML accuracy: > 90% on held-out test set before any model deployment"),
      h2("9.3 Quality Gates"),
      bullet("All PRs must pass lint (ESLint + Prettier), type check (tsc --noEmit), and unit tests"),
      bullet("No PR merged with coverage decrease > 5%"),
      bullet("E2E tests run nightly; failures block next release"),
      bullet("Load tests run before each major release"),
      pageBreak(),
      h1("10. Project Structure"),
      code("verifai/"),
      code("├── apps/"),
      code("│   ├── web/                    # Next.js 14 web application"),
      code("│   │   ├── app/                # App Router pages"),
      code("│   │   │   ├── (auth)/         # Login, register, forgot-password"),
      code("│   │   │   ├── (dashboard)/    # Protected: analyze, history, settings"),
      code("│   │   │   └── api/            # API route handlers"),
      code("│   │   ├── components/         # React components"),
      code("│   │   │   ├── ui/             # shadcn/ui base components"),
      code("│   │   │   ├── analysis/       # AnalysisCard, VerdictBadge, ScoreGauge"),
      code("│   │   │   └── dashboard/      # Charts, stats, history table"),
      code("│   │   ├── lib/                # Supabase client, API clients, utils"),
      code("│   │   ├── hooks/              # React Query hooks"),
      code("│   │   └── stores/             # Zustand state"),
      code("│   └── mobile/                 # React Native app"),
      code("│"),
      code("├── packages/"),
      code("│   ├── types/                  # Shared TypeScript types"),
      code("│   ├── schemas/                # Zod validation schemas"),
      code("│   └── utils/                  # Shared utility functions"),
      code("├── services/"),
      code("│   ├── ml-service/             # Python FastAPI ML inference"),
      code("│   │   ├── models/             # BERT, RoBERTa model files"),
      code("│   │   ├── pipelines/          # Preprocessing, ensemble, explainer"),
      code("│   │   └── api/                # FastAPI routes"),
      code("│   └── scraper/                # Playwright scraping service"),
      code("├── supabase/"),
      code("│   ├── functions/              # Edge Functions (Deno)"),
      code("│   ├── migrations/             # SQL migration files"),
      code("│   └── seed.sql                # Development seed data"),
      code("└── infrastructure/             # Docker, k8s, Terraform configs"),
      pageBreak(),
      h1("11. Definition of Done"),
      bullet("All acceptance criteria from PRD user stories are met"),
      bullet("Feature has unit, integration, and (for P0) E2E test coverage"),
      bullet("Code reviewed and approved by at least 2 engineers"),
      bullet("No P0/P1 bugs outstanding for the feature"),
      bullet("Accessibility audit passed (WCAG 2.1 AA)"),
      bullet("API documentation updated in Swagger/OpenAPI spec"),
      bullet("Database migrations reviewed by DBA and tested on staging"),
      bullet("Performance benchmarks met (< 3s p95 response time)"),
      bullet("Security review completed for auth-touching and data-touching changes"),
      bullet("Product Manager sign-off obtained"),
      bullet("Feature flagged and can be safely rolled back"),
    ]
  }]
});

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync("VERIFAI_TRD.docx", buffer);
  console.log("TRD generated successfully!");
});